#!/bin/bash

# Simple GitHub Push - Manual Steps
# Run this to see the exact commands you need

echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "🚀 ShuAI to GitHub - Manual Deployment Steps"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "Since I cannot authenticate with GitHub for you, here are"
echo "the exact commands you need to run:"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "STEP 1: Create GitHub Repository"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "Go to: https://github.com/new"
echo ""
echo "Settings:"
echo "  - Repository name: shuai-agency-site"
echo "  - Description: Production Next.js website for ShuAI - AI agency"
echo "  - Visibility: Public (or Private)"
echo "  - ❌ DO NOT initialize with README, .gitignore, or license"
echo ""
echo "Click: Create repository"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "STEP 2: Get Your GitHub Username"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
read -p "Enter your GitHub username: " username
echo ""

if [ -z "$username" ]; then
  echo "❌ No username provided. Using placeholder."
  username="YOUR_USERNAME"
fi

echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "STEP 3: Run These Commands"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "Copy and paste these commands one by one:"
echo ""
echo "# Navigate to project"
echo "cd /home/user/shuai-agency-site"
echo ""
echo "# Add GitHub remote"
echo "git remote add origin https://github.com/$username/shuai-agency-site.git"
echo ""
echo "# Rename branch to main"
echo "git branch -M main"
echo ""
echo "# Push to GitHub"
echo "git push -u origin main"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "STEP 4: Authentication"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "When prompted for password, use a Personal Access Token:"
echo ""
echo "1. Create token at: https://github.com/settings/tokens/new"
echo "2. Scopes needed: repo (full control)"
echo "3. Copy the token"
echo "4. Use token as password when git prompts"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "STEP 5: After Pushing to GitHub"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "Deploy to Vercel:"
echo ""
echo "1. Go to: https://vercel.com/new"
echo "2. Import repository: https://github.com/$username/shuai-agency-site"
echo "3. Add environment variables (minimum):"
echo "   - OPENAI_API_KEY=sk-your-key"
echo "   - ADMIN_PASSWORD_HASH=\$(see below)"
echo "4. Click Deploy"
echo ""
echo "Generate admin hash:"
echo "node -e \"console.log(require('bcryptjs').hashSync('your-password', 10))\""
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "📚 Full Guides Available:"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "  - QUICKSTART.md - 5-minute deployment"
echo "  - DEPLOYMENT.md - Full detailed guide"
echo "  - README.md - Complete documentation"
echo ""
echo "Repository: https://github.com/$username/shuai-agency-site"
echo ""
